### ISSUE TITLE
Create Homebrew formula

### ISSUE THREAD

**Issue by mattt** [dependabot/cli#1]
We should support installation of the CLI using [Homebrew](https://brew.sh).

**Comment by mattt** [comment]
I created a Homebrew formula (see below), but got the following error when attempting to submit to Homebrew-core:

```
dependabot:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected
```

It looks like we'll have to advertise this repo a bit more before we can submit the formula. I don't think we're interested in maintaining a private tap to host the formula in the meantime, and it shouldn't take too long to meet that criteria.

<details>

<summary>Dependabot.rb</summary>

```ruby
class Dependabot < Formula
  desc "Tool for testing and debugging Dependabot update jobs"
  homepage "https://github.com/dependabot/cli"
  url "https://github.com/dependabot/cli/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "6a78fca822413b8a541ad339fdd95ba6e45fae18cccb8c9ca544fe8550d08517"
  license "MIT"

  head "https://github.com/dependabot/cli.git", branch: "main"

  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on "go" => :build

  def install
    system "go", "build", "-o", "bin/dependabot", "-ldflags", "-X github.com/dependabot/cli/cmd/dependabot/internal/cmd.version=#{version}"

    bin.install "bin/dependabot"
    generate_completions_from_executable(bin/"dependabot", "completion", "-s")
  end

  test do
    assert_match "dependabot version #{version}", shell_output("#{bin}/dependabot --version")
  end
end
```

</details>

**Comment by markdorison** [comment]
I forked and starred to help the stats! 😂

**Comment by nitrocode** [comment]
I also helped with the stats.

The repo now has greater than 100 stars which should allow a contribution to homebrew.

If not, dependabot or GitHub could host its own homebrew tap on its org or create a repo specific tap.

**Comment by jeffwidman** [comment]
We do indeed have enough stars and forks that our contribution passes the Homebrew bar. We don't have enough watchers, but I'm unclear if we have to pass all criteria, or just most of them.

This is open source, anyone is welcome to submit the formula to Homebrew.

I don't think we at GitHub should be prioritizing our time on it, as there's a few other parts of Dependabot that are higher value for the community and require more in-depth knowledge of Dependabot's internals, so that's what we should be spending our time on.

**Comment by LukeCarrier** [comment]
Let's see if we can land Homebrew/homebrew-core#181253 🎉

**Comment by jeffwidman** [comment]
Thanks @LukeCarrier really appreciate you driving this forward!

**Comment by nitrocode** [comment]
Nice work!
