### ISSUE TITLE
Incorrect package manager documentation: `unknown package manager: python`

### ISSUE THREAD

**Issue by rickstaa** [dependabot/cli#140]
I receive a ` failed to run updater: unknown package manager: python` when I try to use the `python` package manager argument given in [the documentation](https://github.com/dependabot/cli#dependabot-update). By inspecting the codebase, I noticed that the CLI works with `pip`. I initially created #139 to fix this but since https://github.com/dependabot/dependabot-core also uses `pip` I think it is better to update the documentation.

**Comment by jakecoffman** [comment]
Yeah that's confusing. It's named `pip` for historical reasons. I've fixed the docs, thanks for the report!
