### ISSUE TITLE
Is it possible to run the cli for git enterprise?

### ISSUE THREAD

**Issue by tunessofia** [dependabot/cli#153]
based on this issue https://github.com/dependabot/cli/issues/134 i tried to change the default host of git because i have a github enterprise instance, but didnt work. received a 401, althought couldnt get more info regarding to where is trying to get access to, if my instance or the github default.

Using the `--debug` didnt provide more info

```
{
  "job": {
    "package-manager": "npm_and_yarn",
    "allowed-updates": [
      {
        "update-type": "all"
      }
    ],
    "source": {
      "provider": "github",
      "repo": "demo-repo",
      "directory": "\/",
      "branch": "develop"
    }
  },
  "credentials": [
    {
      "type": "git_source",
      "host": "my_instance",
      "username": "x-access-token",
      "password": "my_token"
    },
    {
      "type": "npm_registry",
      "registry": "my_registry",
      "token": "my_token"
    }
  ]
}
```

Am i doing something wrong or is really not possible to access a different instance other than github.com ?

**Comment by jakecoffman** [comment]
The `source` property has `hostname` and `api-endpoint` which you can set to your enterprise instance. Also note it looks like you need to add the org to the `repo`. Here's an example in yaml format:

```yaml
source:
    provider: github
    repo: my-org/demo-repo
    directory: /.
    hostname: example.com
    api-endpoint: https://example.com/api/v3
```

When I run this it tries to clone the repo from example.com:

```
updater | 2023/07/20 12:57:57 INFO Starting job processing
  proxy | 2023/07/20 12:57:59 [002] GET https://example.com:443/my-org/demo-repo/info/refs?service=git-upload-pack
```

Once I add in the credentials the logs look like this:

```
updater | 2023/07/20 12:59:02 INFO Starting job processing
  proxy | 2023/07/20 12:59:03 [002] GET https://example.com:443/my-org/demo-repo/info/refs?service=git-upload-pack
  proxy | 2023/07/20 12:59:03 [002] * authenticating git server request (host: example.com)
```

**Comment by tunessofia** [comment]
> The `source` property has `hostname` and `api-endpoint` which you can set to your enterprise instance. Also note it looks like you need to add the org to the `repo`. Here's an example in yaml format:
> 
> ```yaml
> source:
>     provider: github
>     repo: my-org/demo-repo
>     directory: /.
>     hostname: example.com
>     api-endpoint: https://example.com/api/v3
> ```
> 
> When I run this it tries to clone the repo from example.com:
> 
> ```
> updater | 2023/07/20 12:57:57 INFO Starting job processing
>   proxy | 2023/07/20 12:57:59 [002] GET https://example.com:443/my-org/demo-repo/info/refs?service=git-upload-pack
> ```
> 
> Once I add in the credentials the logs look like this:
> 
> ```
> updater | 2023/07/20 12:59:02 INFO Starting job processing
>   proxy | 2023/07/20 12:59:03 [002] GET https://example.com:443/my-org/demo-repo/info/refs?service=git-upload-pack
>   proxy | 2023/07/20 12:59:03 [002] * authenticating git server request (host: example.com)
> ```

Thanks for the info! I've tried to add the properties you said, but i keep receiving the 401, i also noticed a difference between your output and mine. I'm running the following command:
```
./dependabot update -f job.yaml
```

and only receive this output:
```
cli | 2023/07/20 13:24:35 Adding missing credentials-metadata into job definition
cli | 2023/07/20 13:24:35 failed to run updater: failed request to GitHub API: 401 Unauthorized
```

yours states `updater` and `proxy` logging...

**Comment by jakecoffman** [comment]
Oh interesting, you're actually running into this credential security check: https://github.com/dependabot/cli/blob/d2773b659766f4aaf71ce3751287fd11ebd358a0/internal/infra/run.go#L181

That was written with only github.com in mind, it's trying to check to make sure the token doesn't have write access but since you're on enterprise it's looking in the wrong place. It should use the `api-endpoint` in the input file. I'll fix that!

**Comment by jakecoffman** [comment]
If you update to the latest Dependabot CLI it should be working now. Thanks for the report!
