### ISSUE TITLE
Run dependabot cli for my local branch

### ISSUE THREAD

**Issue by eduardoacskimlinks** [dependabot/cli#174]
# Issue

We only have the budget to include advanced security features to test our vulnerabilities if we release our code to production (aka default branch).

So, I would like to test the dependable CLI against a local copy of my repository before creating my pull requests.

Is this doable? If it is, how can I run it? 

Note: Due to security policies, I don't want to expose any credentials on the run.

**Comment by jakecoffman** [comment]
You can do `dependabot update <ecosystem> <org>/<name> --local .` and the CLI will load the given directory (`.` in this case) and use it as the repository. We use the `local` flag to test without having to push up the changes to GitHub sometimes. 

I can't guarantee it will work for every ecosystem as I haven't tested that will all of them, but if you run into problems you're welcome to file an issue.

**Comment by eduardoacskimlinks** [comment]
Thanks for sharing this, @jakecoffman. I saw it working locally even when I used it in a repository outside the organisation or the wrong repository, so it solved this issue. 

I have a couple of questions regarding the command and the output. 

1. What is the reason behind using organisation and name for a local test? I am concerned that the CLI may use local GitHub credentials to reach out to the organisation
2. Could it be customised the final report to include the severity?

Note: I closed the ticket as the questions are unrelated to this issue

**Comment by jakecoffman** [comment]
It would probably work with a fake org and name. The Dependabot CLI will try to automatically use a credential stored in the environment variable LOCAL_GITHUB_ACCESS_TOKEN, so if that isn't present it won't attempt to use credentials. 

The CLI and Updater don't make any calls to the GitHub Advisory Database, so finding advisories and their severity would have to be something scripted after the CLI runs. 

Good luck!

**Comment by eduardoacskimlinks** [comment]
That was helpful, thanks @jakecoffman.
