### ISSUE TITLE
Provide a `dependabot new-ecosystem` command

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/cli#194]
We're recently trying to be more agile at providing support for new ecosystems in dependabot-core, and I thought it would be nice for people to be able to bootstrap a new ecosystem more easily and let them get all the boilerplate code needed to implement a new  by running a command.

And I thought maybe that could be added to the CLI.

One potential problem is that it would couple the CLI with the particular structure of the dependabot-core repo, which is not ideal.

Opening this issue to hear thoughts & opinions about this!

**Comment by jeffwidman** [comment]
I don't think this is a great idea, at least at the project's current stage of maturity.... and that goes for both `cli` and `dependabot-core`!

> One potential problem is that it would couple the CLI with the particular structure of the dependabot-core repo, which is not ideal.

This is the primary reason why. If we look at how the `cli` wraps `dependabot-core`, there's actually the possibility for a new ecosystem to actually replace `dependabot-core` entirely... granted, it'd likely be a very primitive implementation, but there is the possibility of creating relatively clean abstractions within the `cli` pipeline such that someone could write a fetcher/updater in their own native language and then plug the outputs of that back to the `cli` which could then create the PRs.

The reality though is that's pretty hazy as an idea, and like all abstractions, probably a little messier in reality than what we dream about. 😄 

But for now, I think saying "here's a template, write it in ruby using this format" actually results in calcifying not only the `cli`, but also the structure of `dependabot-core`.
