### ISSUE TITLE
Provide installation options on Linux and BSD

### ISSUE THREAD

**Issue by mattt** [dependabot/cli#2]
We should provide a convenient way to install the `dependabot` on Linux platforms.

**Comment by jeffwidman** [comment]
I realize it'd be convenient to support those upstream package managers, but I don't foresee us officially supporting those anytime in the foreseeable future... This is a `go`-based program, a simple `go get` is trivial, and anyone running Linux/BSD (or even playing with :dependabot:!) should be very comfortable following our [existing install instructions](https://github.com/dependabot/cli#installation).

This is open source, so anyone who wants is welcome to drive unofficial installation methods with those ecosystems package managers. 

I'm going to close, as I just don't think there's a clear next action related to this repo here.
