### ISSUE TITLE
Unknown Package Manager Error when Running dependabot test Command

### ISSUE THREAD

**Issue by vikram-thalithaje** [dependabot/cli#362]
### Description
I am trying to run the `dependabot test` command but keep encountering an "unknown package manager" error.

### Steps to Reproduce (Tried steps 1 and 2, just in case)
1. Run the command: `dependabot test --proxy-image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest -f dependabot.yml`
2. `dependabot test -f dependabot.yml`
3. The response I get is:
`cli | 2024/09/26 09:53:41 unknown package manager: `
4. I also tried changing the package manager to npm, just to see if I get a different error, but it was the same response.

My dependabot.yml looks like 
<img width="644" alt="image" src="https://github.com/user-attachments/assets/3f62d170-8bf2-4573-ac0b-36e1e8c56d75">

Not sure what I am missing here.

Environment
1. CLI Version - `dependabot version v1.54.0`
2. OS Version - `ProductName: macOS, ProductVersion: 12.3, BuildVersion: 21E230`
3. Nuget Version - `NuGet Version: 6.3.1.1`

**Comment by rhyskoedijk** [comment]
@vikram-thalithaje dependabot-cli doesn't accept `dependabot.yml` as an input file, you need to transform it in to a [job description file](https://github.com/dependabot/cli?tab=readme-ov-file#job-description-file).
